// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentWebsite.Data;

#nullable disable

namespace StudentWebsite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251218131600_InitialMigrations")]
    partial class InitialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentWebsite.Models.Account", b =>
                {
                    b.Property<int>("ACC_Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ACC_Index"));

                    b.Property<string>("ACC_Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ACC_Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ACC_UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ACC_Index");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("StudentWebsite.Models.Activity", b =>
                {
                    b.Property<int>("ACT_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ACT_Id"));

                    b.Property<string>("ACT_Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("ACT_IsGranted")
                        .HasColumnType("bit");

                    b.Property<string>("ACT_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ORG_Id")
                        .HasColumnType("int");

                    b.Property<int>("STUD_Id")
                        .HasColumnType("int");

                    b.HasKey("ACT_Id");

                    b.HasIndex("ORG_Id");

                    b.HasIndex("STUD_Id");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("StudentWebsite.Models.ActivityStatus", b =>
                {
                    b.Property<int>("ACT_StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ACT_StatusId"));

                    b.Property<int>("ACC_Index")
                        .HasColumnType("int");

                    b.Property<int>("ACT_Id")
                        .HasColumnType("int");

                    b.Property<bool>("ACT_IsGranted")
                        .HasColumnType("bit");

                    b.Property<string>("ACT_Notify")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ACT_StatusId");

                    b.HasIndex("ACC_Index");

                    b.HasIndex("ACT_Id");

                    b.ToTable("ActivityStatuses");
                });

            modelBuilder.Entity("StudentWebsite.Models.Locker", b =>
                {
                    b.Property<int>("LOCK_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LOCK_Id"));

                    b.Property<DateTime>("LOCK_DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LOCK_IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("LOCK_Spot")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("STUD_Id")
                        .HasColumnType("int");

                    b.HasKey("LOCK_Id");

                    b.HasIndex("STUD_Id");

                    b.ToTable("Lockers");
                });

            modelBuilder.Entity("StudentWebsite.Models.LockerStatus", b =>
                {
                    b.Property<int>("LOCK_StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LOCK_StatusId"));

                    b.Property<int>("ACC_Index")
                        .HasColumnType("int");

                    b.Property<int>("LOCK_Id")
                        .HasColumnType("int");

                    b.Property<bool>("LOCK_IsGranted")
                        .HasColumnType("bit");

                    b.Property<string>("LOCK_Notify")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LOCK_StatusId");

                    b.HasIndex("ACC_Index");

                    b.HasIndex("LOCK_Id");

                    b.ToTable("LockerStatuses");
                });

            modelBuilder.Entity("StudentWebsite.Models.Organizer", b =>
                {
                    b.Property<int>("ORG_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ORG_Id"));

                    b.Property<string>("ORG_FName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ORG_LName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ORG_MiddleI")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("ORG_Organization")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ORG_Id");

                    b.ToTable("Organizers");
                });

            modelBuilder.Entity("StudentWebsite.Models.Parking", b =>
                {
                    b.Property<int>("PARK_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PARK_Id"));

                    b.Property<DateTime>("PARK_DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PARK_IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("PARK_Schedule")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("PARK_Spot")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("PARK_VehicleModel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PARK_VehicleType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("STUD_Id")
                        .HasColumnType("int");

                    b.HasKey("PARK_Id");

                    b.HasIndex("STUD_Id");

                    b.ToTable("Parkings");
                });

            modelBuilder.Entity("StudentWebsite.Models.ParkingStatus", b =>
                {
                    b.Property<int>("PARK_StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PARK_StatusId"));

                    b.Property<int>("ACC_Index")
                        .HasColumnType("int");

                    b.Property<int>("PARK_Id")
                        .HasColumnType("int");

                    b.Property<bool>("PARK_IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("PARK_Notify")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PARK_StatusId");

                    b.HasIndex("ACC_Index");

                    b.HasIndex("PARK_Id");

                    b.ToTable("ParkingStatuses");
                });

            modelBuilder.Entity("StudentWebsite.Models.Student", b =>
                {
                    b.Property<int>("STUD_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("STUD_Id"));

                    b.Property<int>("ACC_Index")
                        .HasColumnType("int");

                    b.Property<string>("STUD_Course")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("STUD_StudentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("STUD_YearLevel")
                        .HasColumnType("int");

                    b.HasKey("STUD_Id");

                    b.HasIndex("ACC_Index");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudentWebsite.Models.Activity", b =>
                {
                    b.HasOne("StudentWebsite.Models.Organizer", "Organizer")
                        .WithMany()
                        .HasForeignKey("ORG_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentWebsite.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("STUD_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizer");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentWebsite.Models.ActivityStatus", b =>
                {
                    b.HasOne("StudentWebsite.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("ACC_Index")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentWebsite.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ACT_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("StudentWebsite.Models.Locker", b =>
                {
                    b.HasOne("StudentWebsite.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("STUD_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentWebsite.Models.LockerStatus", b =>
                {
                    b.HasOne("StudentWebsite.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("ACC_Index")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentWebsite.Models.Locker", "Locker")
                        .WithMany()
                        .HasForeignKey("LOCK_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Locker");
                });

            modelBuilder.Entity("StudentWebsite.Models.Parking", b =>
                {
                    b.HasOne("StudentWebsite.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("STUD_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentWebsite.Models.ParkingStatus", b =>
                {
                    b.HasOne("StudentWebsite.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("ACC_Index")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentWebsite.Models.Parking", "Parking")
                        .WithMany()
                        .HasForeignKey("PARK_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Parking");
                });

            modelBuilder.Entity("StudentWebsite.Models.Student", b =>
                {
                    b.HasOne("StudentWebsite.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("ACC_Index")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
